### ISSUE TITLE
Mod makes Server Logs unreadable

### ISSUE THREAD

**Issue by LendirHijau** [mastery3/sharpness6#15] opened 2024-07-31 16:24 UTC
when using the mod, server logs become something like this:

[23:21:24 INFO]: menu.preparingSpawn
[23:21:24 INFO]: menu.preparingSpawn
[23:21:24 INFO]: Time elapsed: 946 ms
[23:21:24 INFO]: Done (3.835s)! For help, type "help"
[23:21:38 INFO]: [Not Secure] chat.type.announcement
[23:21:39 INFO]: [Not Secure] chat.type.announcement
[23:21:43 INFO]: [Not Secure] chat.type.announcement

when what supposed to be happening is this:

[23:22:50 INFO]: Preparing spawn area: 0%
[23:22:50 INFO]: Preparing spawn area: 0%
[23:22:50 INFO]: Time elapsed: 1015 ms
[23:22:50 INFO]: Done (3.965s)! For help, type "help"
[23:22:55 INFO]: [Not Secure] [Server] hello
[23:22:58 INFO]: [Not Secure] [Server] test 123
[23:23:04 INFO]: [Not Secure] [Server] it works here rip

because of the mod, i can't read what people says and other important stuff.

**Comment by LendirHijau** [comment] 2024-07-31 16:26
heres a longer ver (while using the mod):

[23:21:20] [Server thread/INFO]: Starting minecraft server version 1.21
[23:21:20] [Server thread/INFO]: Loading properties
[23:21:20] [Server thread/INFO]: Default game type: SURVIVAL
[23:21:20] [Server thread/INFO]: Generating keypair
[23:21:20] [Server thread/INFO]: Starting Minecraft server on *:25565
[23:21:20] [Server thread/INFO]: Using default channel type
[23:21:21] [Server thread/INFO]: Preparing level "world"
[23:21:24] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[23:21:24] [Worker-Main-5/INFO]: menu.preparingSpawn
[23:21:24] [Worker-Main-5/INFO]: menu.preparingSpawn
[23:21:24] [Server thread/INFO]: Time elapsed: 946 ms
[23:21:24] [Server thread/INFO]: Done (3.835s)! For help, type "help"
[23:21:38] [Server thread/INFO]: [Not Secure] chat.type.announcement
[23:21:39] [Server thread/INFO]: [Not Secure] chat.type.announcement
[23:21:43] [Server thread/INFO]: [Not Secure] chat.type.announcement
[23:22:09] [Server thread/INFO]: commands.stop.stopping
[23:22:09] [Server thread/INFO]: Stopping server
[23:22:09] [Server thread/INFO]: Saving players
[23:22:09] [Server thread/INFO]: Saving worlds

while not using the mod:

[23:22:45] [Server thread/INFO]: Starting minecraft server version 1.21
[23:22:45] [Server thread/INFO]: Loading properties
[23:22:45] [Server thread/INFO]: Default game type: SURVIVAL
[23:22:45] [Server thread/INFO]: Generating keypair
[23:22:45] [Server thread/INFO]: Starting Minecraft server on *:25565
[23:22:46] [Server thread/INFO]: Using default channel type
[23:22:46] [Server thread/INFO]: Preparing level "world"
[23:22:49] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[23:22:50] [Worker-Main-6/INFO]: Preparing spawn area: 0%
[23:22:50] [Worker-Main-6/INFO]: Preparing spawn area: 0%
[23:22:50] [Server thread/INFO]: Time elapsed: 1015 ms
[23:22:50] [Server thread/INFO]: Done (3.965s)! For help, type "help"
[23:22:55] [Server thread/INFO]: [Not Secure] [Server] hello
[23:22:58] [Server thread/INFO]: [Not Secure] [Server] test 123
[23:23:04] [Server thread/INFO]: [Not Secure] [Server] it works here rip
[23:23:19] [Server thread/INFO]: Stopping the server
[23:23:19] [Server thread/INFO]: Stopping server
[23:23:19] [Server thread/INFO]: Saving players
[23:23:19] [Server thread/INFO]: Saving worlds

**Comment by mastery3** [comment] 2024-07-31 20:52
Duplicate of #7

**Closed as not planned** 2024-07-31 20:53 UTC
Labels: bug, duplicate
